/*
  File Client_Node.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

class __lclient_1 extends KlavaProcess {
  // variables
  // used definition names

  public __lclient_1() {}

  public void execute() throws KlavaException {
    out( new KString( "client" ), self ) ;
  }
}
// main class
public class Client_Node {
  static public void main( String args[] ) throws IOException, KlavaException {
    KlavaApplication app = new KlavaApplication();
    Node lclient = new Node( "lclient", 14000, args[0], Integer.parseInt( args[1] ) );
    app.addNode(lclient) ;
    lclient.addProcess( new __lclient_1() ) ;
    app.startNodes();
    app.waitForNodesAndTerminate();
  }
}
