/*
  File Mstore3.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

class __shop31_1 extends KlavaProcess {
  // variables
  protected LogicalLocality succ = new LogicalLocality( "succ" ) ;
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop31_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), succ, self ) ;
    out( new KString( "id1" ), new KInteger( 10 ), new KInteger( 12 ), self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 18 ), self ) ;
    out( new KString( "id3" ), new KInteger( 15 ), new KInteger( 15 ), self ) ;
  }
}
class __shop32_1 extends KlavaProcess {
  // variables
  protected LogicalLocality succ = new LogicalLocality( "succ" ) ;
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop32_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), succ, self ) ;
    out( new KString( "id1" ), new KInteger( 6 ), new KInteger( 11 ), self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 15 ), self ) ;
    out( new KString( "id3" ), new KInteger( 13 ), new KInteger( 29 ), self ) ;
    out( new KString( "id4" ), new KInteger( 16 ), new KInteger( 6 ), self ) ;
  }
}
class __shop33_1 extends KlavaProcess {
  // variables
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop33_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), finish, self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 17 ), self ) ;
    out( new KString( "id3" ), new KInteger( 12 ), new KInteger( 23 ), self ) ;
    out( new KString( "id4" ), new KInteger( 11 ), new KInteger( 16 ), self ) ;
  }
}
class __l3_1 extends KlavaProcess {
  // variables
  protected LogicalLocality startS = new LogicalLocality( "startS" ) ;
  // used definition names

  public __l3_1() {}

  public void execute() throws KlavaException {
    out( new KString( "start" ), startS, self ) ;
  }
}
// main class
public class Mstore3 {
  static public void main( String args[] ) throws IOException, KlavaException {
    KlavaApplication app = new KlavaApplication();
    Node shop31 = new Node( "shop31", 13001, args[0], Integer.parseInt( args[1] ) );
    shop31.addToEnv( "succ", NetUtils.createNodeAddress("localhost:13002") ) ;
    shop31.addToEnv( "finish", NetUtils.createNodeAddress("localhost:13005") ) ;
    shop31.addToEnv( "s", NetUtils.createNodeAddress("localhost:13004") ) ;
    app.addNode(shop31) ;
    shop31.addProcess( new __shop31_1() ) ;
    Node shop32 = new Node( "shop32", 13002, args[0], Integer.parseInt( args[1] ) );
    shop32.addToEnv( "succ", NetUtils.createNodeAddress("localhost:13003") ) ;
    shop32.addToEnv( "finish", NetUtils.createNodeAddress("localhost:13005") ) ;
    shop32.addToEnv( "s", NetUtils.createNodeAddress("localhost:13004") ) ;
    app.addNode(shop32) ;
    shop32.addProcess( new __shop32_1() ) ;
    Node shop33 = new Node( "shop33", 13003, args[0], Integer.parseInt( args[1] ) );
    shop33.addToEnv( "finish", NetUtils.createNodeAddress("localhost:13005") ) ;
    shop33.addToEnv( "s", NetUtils.createNodeAddress("localhost:13004") ) ;
    app.addNode(shop33) ;
    shop33.addProcess( new __shop33_1() ) ;
    Node l3 = new Node( "l3", 13004, args[0], Integer.parseInt( args[1] ) );
    l3.addToEnv( "startS", NetUtils.createNodeAddress("localhost:13001") ) ;
    app.addNode(l3) ;
    l3.addProcess( new __l3_1() ) ;
    app.startNodes();
    app.waitForNodesAndTerminate();
  }
}
