/*
  File Mstore2.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

class __shop21_1 extends KlavaProcess {
  // variables
  protected LogicalLocality succ = new LogicalLocality( "succ" ) ;
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop21_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), succ, self ) ;
    out( new KString( "id1" ), new KInteger( 10 ), new KInteger( 12 ), self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 10 ), self ) ;
    out( new KString( "id3" ), new KInteger( 15 ), new KInteger( 9 ), self ) ;
  }
}
class __shop22_1 extends KlavaProcess {
  // variables
  protected LogicalLocality succ = new LogicalLocality( "succ" ) ;
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop22_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), finish, self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 19 ), self ) ;
    out( new KString( "id3" ), new KInteger( 12 ), new KInteger( 29 ), self ) ;
    out( new KString( "id4" ), new KInteger( 11 ), new KInteger( 17 ), self ) ;
  }
}
class __shop23_1 extends KlavaProcess {
  // variables
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop23_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), finish, self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 21 ), self ) ;
    out( new KString( "id3" ), new KInteger( 12 ), new KInteger( 10 ), self ) ;
    out( new KString( "id4" ), new KInteger( 11 ), new KInteger( 27 ), self ) ;
  }
}
class __l2_1 extends KlavaProcess {
  // variables
  protected LogicalLocality startS = new LogicalLocality( "startS" ) ;
  // used definition names

  public __l2_1() {}

  public void execute() throws KlavaException {
    out( new KString( "start" ), startS, self ) ;
  }
}
// main class
public class Mstore2 {
  static public void main( String args[] ) throws IOException, KlavaException {
    KlavaApplication app = new KlavaApplication();
    Node shop21 = new Node( "shop21", 12001, args[0], Integer.parseInt( args[1] ) );
    shop21.addToEnv( "succ", NetUtils.createNodeAddress("localhost:12002") ) ;
    shop21.addToEnv( "finish", NetUtils.createNodeAddress("localhost:12005") ) ;
    shop21.addToEnv( "s", NetUtils.createNodeAddress("localhost:12004") ) ;
    app.addNode(shop21) ;
    shop21.addProcess( new __shop21_1() ) ;
    Node shop22 = new Node( "shop22", 12002, args[0], Integer.parseInt( args[1] ) );
    shop22.addToEnv( "succ", NetUtils.createNodeAddress("localhost:12003") ) ;
    shop22.addToEnv( "finish", NetUtils.createNodeAddress("localhost:12005") ) ;
    shop22.addToEnv( "s", NetUtils.createNodeAddress("localhost:12004") ) ;
    app.addNode(shop22) ;
    shop22.addProcess( new __shop22_1() ) ;
    Node shop23 = new Node( "shop23", 12003, args[0], Integer.parseInt( args[1] ) );
    shop23.addToEnv( "finish", NetUtils.createNodeAddress("localhost:12005") ) ;
    shop23.addToEnv( "s", NetUtils.createNodeAddress("localhost:12004") ) ;
    app.addNode(shop23) ;
    shop23.addProcess( new __shop23_1() ) ;
    Node l2 = new Node( "l2", 12004, args[0], Integer.parseInt( args[1] ) );
    l2.addToEnv( "startS", NetUtils.createNodeAddress("localhost:12001") ) ;
    app.addNode(l2) ;
    l2.addProcess( new __l2_1() ) ;
    app.startNodes();
    app.waitForNodesAndTerminate();
  }
}
