/*
  File Mstore1.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

class __shop11_1 extends KlavaProcess {
  // variables
  protected LogicalLocality succ = new LogicalLocality( "succ" ) ;
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop11_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), succ, self ) ;
    out( new KString( "id1" ), new KInteger( 10 ), new KInteger( 11 ), self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 15 ), self ) ;
    out( new KString( "id3" ), new KInteger( 15 ), new KInteger( 8 ), self ) ;
  }
}
class __shop12_1 extends KlavaProcess {
  // variables
  protected LogicalLocality succ = new LogicalLocality( "succ" ) ;
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop12_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), succ, self ) ;
    out( new KString( "id1" ), new KInteger( 6 ), new KInteger( 15 ), self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 15 ), self ) ;
    out( new KString( "id3" ), new KInteger( 13 ), new KInteger( 9 ), self ) ;
    out( new KString( "id4" ), new KInteger( 16 ), new KInteger( 6 ), self ) ;
  }
}
class __shop13_1 extends KlavaProcess {
  // variables
  protected LogicalLocality finish = new LogicalLocality( "finish" ) ;
  protected LogicalLocality s = new LogicalLocality( "s" ) ;
  // used definition names

  public __shop13_1() {}

  public void execute() throws KlavaException {
    out( new KString( "next" ), finish, self ) ;
    out( new KString( "id2" ), new KInteger( 15 ), new KInteger( 10 ), self ) ;
    out( new KString( "id3" ), new KInteger( 12 ), new KInteger( 8 ), self ) ;
    out( new KString( "id4" ), new KInteger( 11 ), new KInteger( 6 ), self ) ;
  }
}
class __l1_1 extends KlavaProcess {
  // variables
  protected LogicalLocality startS = new LogicalLocality( "startS" ) ;
  // used definition names

  public __l1_1() {}

  public void execute() throws KlavaException {
    out( new KString( "start" ), startS, self ) ;
  }
}
// main class
public class Mstore1 {
  static public void main( String args[] ) throws IOException, KlavaException {
    KlavaApplication app = new KlavaApplication();
    Node shop11 = new Node( "shop11", 11001, args[0], Integer.parseInt( args[1] ) );
    shop11.addToEnv( "succ", NetUtils.createNodeAddress("localhost:11002") ) ;
    shop11.addToEnv( "finish", NetUtils.createNodeAddress("localhost:11005") ) ;
    shop11.addToEnv( "s", NetUtils.createNodeAddress("localhost:11004") ) ;
    app.addNode(shop11) ;
    shop11.addProcess( new __shop11_1() ) ;
    Node shop12 = new Node( "shop12", 11002, args[0], Integer.parseInt( args[1] ) );
    shop12.addToEnv( "succ", NetUtils.createNodeAddress("localhost:11003") ) ;
    shop12.addToEnv( "finish", NetUtils.createNodeAddress("localhost:11005") ) ;
    shop12.addToEnv( "s", NetUtils.createNodeAddress("localhost:11004") ) ;
    app.addNode(shop12) ;
    shop12.addProcess( new __shop12_1() ) ;
    Node shop13 = new Node( "shop13", 11003, args[0], Integer.parseInt( args[1] ) );
    shop13.addToEnv( "finish", NetUtils.createNodeAddress("localhost:11005") ) ;
    shop13.addToEnv( "s", NetUtils.createNodeAddress("localhost:11004") ) ;
    app.addNode(shop13) ;
    shop13.addProcess( new __shop13_1() ) ;
    Node l1 = new Node( "l1", 11004, args[0], Integer.parseInt( args[1] ) );
    l1.addToEnv( "startS", NetUtils.createNodeAddress("localhost:11001") ) ;
    app.addNode(l1) ;
    l1.addProcess( new __l1_1() ) ;
    app.startNodes();
    app.waitForNodesAndTerminate();
  }
}
