/*
  File prova.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

class __client1_1 extends KlavaProcess {
  // variables
  protected LogicalLocality startL = new LogicalLocality( "startL" ) ;
  // used definition names
  protected FindItem __dummy_FindItem;

  public __client1_1() {}

  public void execute() throws KlavaException {
    eval(  new FindItem( new KString( "id1" ), new KInteger( 500 ), new KString( "client1" ) ), startL ) ;
  }
}
// main class
public class prova {
  static public void main( String args[] ) throws IOException, KlavaException {
    KlavaApplication app = new KlavaApplication();
    Node client1 = new Node( "client1", 16001, args[0], Integer.parseInt( args[1] ) );
    client1.addToEnv( "startL", NetUtils.createNodeAddress("localhost:11004") ) ;
    app.addNode(client1) ;
    client1.addProcess( new __client1_1() ) ;
    app.startNodes();
    app.waitForNodesAndTerminate();
  }
}
