/*
  File HelloDirect.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

public class HelloDirect extends NodeCoordinator {
  // parameters
  protected Locality remote;
  // variables
  protected PhysicalLocality peer;
  // used definition names
  protected HelloSenderProc __dummy_HelloSenderProc;

  public HelloDirect(
    Locality remote
  ) {
    // parameters
    this.remote = remote ;
  }

  public void execute() throws KlavaException {
    eval(  new __ChP___1( peer ), self ) ;
    dirconnect(remote) ;
    eval(  new HelloSenderProc( remote ), self ) ;
  }

  // Children

  class __ChP___1 extends KlavaProcess {
    // parameters
    protected PhysicalLocality peer;
    // variables
    // used definition names

    public __ChP___1(
      PhysicalLocality peer
    ) {
      // parameters
      this.peer = peer ;
    }

    public void execute() throws KlavaException {
      peer = new PhysicalLocality() ;
      acceptconn(peer) ;
    }
  }
}
