/*
  File nodes_orc.java

  Generated by xklaim compiler
*/

import java.io.* ;
import Klava.* ;

class __hotel_1 extends KlavaProcess {
  // variables
  protected LogicalLocality compensator = new LogicalLocality( "compensator" ) ;
  protected LogicalLocality prenotazione = new LogicalLocality( "prenotazione" ) ;
  protected LogicalLocality risposta = new LogicalLocality( "risposta" ) ;
  // used definition names

  public __hotel_1() {}

  public void execute() throws KlavaException {
    out( new KString( "doppia" ), new KInteger( 2 ), new KInteger( 60 ), self ) ;
    out( new KString( "singola" ), new KInteger( 2 ), new KInteger( 40 ), self ) ;
  }
}
class __volo_1 extends KlavaProcess {
  // variables
  protected LogicalLocality compensator = new LogicalLocality( "compensator" ) ;
  protected LogicalLocality prenotazione = new LogicalLocality( "prenotazione" ) ;
  protected LogicalLocality risposta = new LogicalLocality( "risposta" ) ;
  // used definition names

  public __volo_1() {}

  public void execute() throws KlavaException {
    out( new KString( "milano" ), new KInteger( 2 ), new KInteger( 45 ), self ) ;
    out( new KString( "roma" ), new KInteger( 2 ), new KInteger( 52 ), self ) ;
  }
}
class __prenotazione_1 extends KlavaProcess {
  // variables
  protected KInteger count;
  protected KInteger gcount;
  protected KInteger numero;
  protected KInteger id;
  protected KInteger x;
  protected KInteger tot;
  protected KInteger prezzo;
  protected KString stringa;
  protected Locality dloc;
  protected KBoolean _while_exp_1;
  protected Tuple __tuple_1;
  protected Tuple __tuple_2;
  protected Tuple __tuple_3;
  protected KInteger __backup_1_tot;
  protected KInteger __backup_2_count;
  protected KBoolean __to_1;
  protected LogicalLocality risposta = new LogicalLocality( "risposta" ) ;
  // used definition names

  public __prenotazione_1() {}

  public void execute() throws KlavaException {
    gcount = new KInteger( 0 ) ;
    _while_exp_1 = new KBoolean( true ) ;
    while ( _while_exp_1.booleanValue() ) {
      __tuple_1 = new Tuple() ;
      id = new KInteger() ;
      __tuple_1.add( id ) ;
      stringa = new KString() ;
      __tuple_1.add( stringa ) ;
      numero = new KInteger() ;
      __tuple_1.add( numero ) ;
      prezzo = new KInteger() ;
      __tuple_1.add( prezzo ) ;
      dloc = new PhysicalLocality() ;
      __tuple_1.add( dloc ) ;
      in( __tuple_1, self ) ;
      __tuple_2 = new Tuple() ;
      __tuple_2.add( gcount ) ;
      __tuple_2.add( id ) ;
      __tuple_2.add( stringa ) ;
      __tuple_2.add( numero ) ;
      __tuple_2.add( prezzo ) ;
      __tuple_2.add( dloc ) ;
      out( __tuple_2, self ) ;
      gcount = new KInteger( gcount.intValue() + 1 ) ;
      __tuple_3 = new Tuple() ;
      __tuple_3.add( id ) ;
      __backup_1_tot = tot ;
      tot = new KInteger() ;
      __tuple_3.add( tot ) ;
      __backup_2_count = count ;
      count = new KInteger() ;
      __tuple_3.add( count ) ;
      __to_1 = new KBoolean( in_nb( __tuple_3, self ) ) ;
      if ( ! __to_1.booleanValue() ) {
        tot = __backup_1_tot ;
        count = __backup_2_count ;
      }
      if ( __to_1.booleanValue() ) {
        out( id, new KString( "prenotato" ), new KInteger( tot.intValue() + prezzo.intValue() ), risposta ) ;
      } else {
        out( id, prezzo, new KInteger( 1 ), self ) ;
      }
      _while_exp_1 = new KBoolean( true ) ;
    }
  }
}
class __compensator_1 extends KlavaProcess {
  // variables
  protected KString stringa;
  protected KInteger numero;
  protected KInteger id;
  protected KInteger count;
  protected KInteger gcount;
  protected KInteger num;
  protected KInteger prezzo;
  protected Locality dloc;
  protected KBoolean _while_exp_2;
  protected Tuple __tuple_4;
  protected KInteger __backup_3_gcount;
  protected KString __backup_4_stringa;
  protected KInteger __backup_5_numero;
  protected KInteger __backup_6_prezzo;
  protected Locality __backup_7_dloc;
  protected KBoolean __to_2;
  protected KBoolean _forall_exp_1;
  protected LogicalLocality volo = new LogicalLocality( "volo" ) ;
  protected LogicalLocality hotel = new LogicalLocality( "hotel" ) ;
  protected LogicalLocality prenotazione = new LogicalLocality( "prenotazione" ) ;
  protected LogicalLocality risposta = new LogicalLocality( "risposta" ) ;
  // used definition names

  public __compensator_1() {}

  public void execute() throws KlavaException {
    _while_exp_2 = new KBoolean( true ) ;
    while ( _while_exp_2.booleanValue() ) {
      id = new KInteger() ;
      in( new KString( "start" ), id, self ) ;
      __tuple_4 = new Tuple() ;
      __tuple_4.setHandleRetrieved(true) ;
      __backup_3_gcount = gcount ;
      gcount = new KInteger() ;
      __tuple_4.add( gcount ) ;
      __tuple_4.add( id ) ;
      __backup_4_stringa = stringa ;
      stringa = new KString() ;
      __tuple_4.add( stringa ) ;
      __backup_5_numero = numero ;
      numero = new KInteger() ;
      __tuple_4.add( numero ) ;
      __backup_6_prezzo = prezzo ;
      prezzo = new KInteger() ;
      __tuple_4.add( prezzo ) ;
      __backup_7_dloc = dloc ;
      dloc = new PhysicalLocality() ;
      __tuple_4.add( dloc ) ;
      __to_2 = new KBoolean( in_nb( __tuple_4, prenotazione ) ) ;
      if ( ! __to_2.booleanValue() ) {
        gcount = __backup_3_gcount ;
        stringa = __backup_4_stringa ;
        numero = __backup_5_numero ;
        prezzo = __backup_6_prezzo ;
        dloc = __backup_7_dloc ;
      }
      _forall_exp_1 = __to_2 ;
      while ( _forall_exp_1.booleanValue() ) {
        num = new KInteger() ;
        prezzo = new KInteger() ;
        in( stringa, num, prezzo, dloc ) ;
        out( stringa, new KInteger( num.intValue() + numero.intValue() ), prezzo, dloc ) ;
        __tuple_4.reset() ;
        __backup_3_gcount = gcount ;
        gcount = new KInteger() ;
        __tuple_4.add( gcount ) ;
        __tuple_4.add( id ) ;
        __backup_4_stringa = stringa ;
        stringa = new KString() ;
        __tuple_4.add( stringa ) ;
        __backup_5_numero = numero ;
        numero = new KInteger() ;
        __tuple_4.add( numero ) ;
        __backup_6_prezzo = prezzo ;
        prezzo = new KInteger() ;
        __tuple_4.add( prezzo ) ;
        __backup_7_dloc = dloc ;
        dloc = new PhysicalLocality() ;
        __tuple_4.add( dloc ) ;
        __to_2 = new KBoolean( in_nb( __tuple_4, prenotazione ) ) ;
        if ( ! __to_2.booleanValue() ) {
          gcount = __backup_3_gcount ;
          stringa = __backup_4_stringa ;
          numero = __backup_5_numero ;
          prezzo = __backup_6_prezzo ;
          dloc = __backup_7_dloc ;
        }
        _forall_exp_1 = __to_2 ;
      }
      out( id, new KString( "compensazione" ), new KInteger( 0 ), risposta ) ;
      _while_exp_2 = new KBoolean( true ) ;
    }
  }
}
// main class
public class nodes_orc {
  static public void main( String args[] ) throws IOException, KlavaException {
    KlavaApplication app = new KlavaApplication();
    Node hotel = new Node( "hotel", 11001, args[0], Integer.parseInt( args[1] ) );
    hotel.addToEnv( "compensator", NetUtils.createNodeAddress("localhost:11004") ) ;
    hotel.addToEnv( "prenotazione", NetUtils.createNodeAddress("localhost:11003") ) ;
    hotel.addToEnv( "risposta", NetUtils.createNodeAddress("localhost:11000") ) ;
    app.addNode(hotel) ;
    hotel.addProcess( new __hotel_1() ) ;
    Node volo = new Node( "volo", 11002, args[0], Integer.parseInt( args[1] ) );
    volo.addToEnv( "compensator", NetUtils.createNodeAddress("localhost:11004") ) ;
    volo.addToEnv( "prenotazione", NetUtils.createNodeAddress("localhost:11003") ) ;
    volo.addToEnv( "risposta", NetUtils.createNodeAddress("localhost:11000") ) ;
    app.addNode(volo) ;
    volo.addProcess( new __volo_1() ) ;
    Node prenotazione = new Node( "prenotazione", 11003, args[0], Integer.parseInt( args[1] ) );
    prenotazione.addToEnv( "risposta", NetUtils.createNodeAddress("localhost:11000") ) ;
    app.addNode(prenotazione) ;
    prenotazione.addProcess( new __prenotazione_1() ) ;
    Node compensator = new Node( "compensator", 11004, args[0], Integer.parseInt( args[1] ) );
    compensator.addToEnv( "volo", NetUtils.createNodeAddress("localhost:11002") ) ;
    compensator.addToEnv( "hotel", NetUtils.createNodeAddress("localhost:11001") ) ;
    compensator.addToEnv( "prenotazione", NetUtils.createNodeAddress("localhost:11003") ) ;
    compensator.addToEnv( "risposta", NetUtils.createNodeAddress("localhost:11000") ) ;
    app.addNode(compensator) ;
    compensator.addProcess( new __compensator_1() ) ;
    app.startNodes();
    app.waitForNodesAndTerminate();
  }
}
